<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Movie;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing movies first to avoid duplicates on re-seed
        Movie::truncate();

        $now = now();

        Movie::insert([
            [
                'title'            => 'Gayong 2',
                'description'      => 'A high-stakes action sequel following the legendary silat master.',
                'genre'            => 'Action',
                'duration'         => 82,
                'release_date'     => '2026-04-10',
                'rating'           => 8.5,
                'poster'           => 'posters/gayong2.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'The Super Mario Galaxy Movie',
                'description'      => 'Mario travels through the cosmos to save Princess Peach.',
                'genre'            => 'Animation',
                'duration'         => 95,
                'release_date'     => '2026-04-01',
                'rating'           => 9.0,
                'poster'           => 'posters/mario.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'LIK: Love Insurance Kompany',
                'description'      => 'A quirky romantic comedy about insuring against heartbreak.',
                'genre'            => 'Comedy',
                'duration'         => 155,
                'release_date'     => '2026-04-09',
                'rating'           => 7.8,
                'poster'           => 'posters/lik.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Project Hail Mary',
                'description'      => 'An astronaut uses science to save humanity from extinction.',
                'genre'            => 'Sci-Fi',
                'duration'         => 130,
                'release_date'     => '2026-04-05',
                'rating'           => 8.7,
                'poster'           => 'posters/phm.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Alas Roban',
                'description'      => 'Travelers face ancient horrors in the infamous Roban forest.',
                'genre'            => 'Horror',
                'duration'         => 111,
                'release_date'     => '2026-04-11',
                'rating'           => 6.4,
                'poster'           => 'posters/alas_roban.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'The Drama',
                'description'      => 'A suspenseful look at the cracks within a perfect relationship.',
                'genre'            => 'Thriller',
                'duration'         => 106,
                'release_date'     => '2026-04-10',
                'rating'           => 7.2,
                'poster'           => 'posters/the_drama.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Malaikat Malam',
                'description'      => 'A supernatural thriller about a nocturnal protector.',
                'genre'            => 'Horror',
                'duration'         => 120,
                'release_date'     => '2026-04-08',
                'rating'           => 6.9,
                'poster'           => 'posters/malaikat_malam.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Mikael: Pemburu Dua Alam',
                'description'      => 'A warrior hunts dangerous entities in the spirit realm.',
                'genre'            => 'Action',
                'duration'         => 115,
                'release_date'     => '2026-04-03',
                'rating'           => 7.5,
                'poster'           => 'posters/mikael_hunter.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'TN 2026',
                'description'      => 'A family drama centered around legacy and honor.',
                'genre'            => 'Drama',
                'duration'         => 140,
                'release_date'     => '2026-04-10',
                'rating'           => 8.0,
                'poster'           => 'posters/tn_2026.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Pee Nak 5',
                'description'      => 'The horror-comedy series returns with a new cursed temple.',
                'genre'            => 'Comedy',
                'duration'         => 119,
                'release_date'     => '2026-04-02',
                'rating'           => 6.2,
                'poster'           => 'posters/pee_nak_5.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Suzzanna: Santet Dosa',
                'description'      => 'The queen of horror returns in a tale of black magic.',
                'genre'            => 'Horror',
                'duration'         => 125,
                'release_date'     => '2026-03-28',
                'rating'           => 7.4,
                'poster'           => 'posters/suzzanna.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Hoppers',
                'description'      => 'An adventure about swapping consciousness with animals.',
                'genre'            => 'Adventure',
                'duration'         => 102,
                'release_date'     => '2026-04-05',
                'rating'           => 7.9,
                'poster'           => 'posters/hoppers.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Ready or Not 2',
                'description'      => 'A deadly game of hide and seek begins with new in-laws.',
                'genre'            => 'Thriller',
                'duration'         => 98,
                'release_date'     => '2026-04-07',
                'rating'           => 8.1,
                'poster'           => 'posters/ready_or_not_2.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Sunshine Women\'s Choir',
                'description'      => 'A baby girl is born inside a women\'s prison, welcomed by four inmates each burdened by a painful past.',
                'genre'            => 'Drama',
                'duration'         => 129,
                'release_date'     => '2026-01-15',
                'rating'           => 8.8,
                'poster'           => 'posters/sunshine.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Pegasus 3',
                'description'      => 'A high-speed racing film about redemption on the track.',
                'genre'            => 'Sport',
                'duration'         => 122,
                'release_date'     => '2026-02-15',
                'rating'           => 7.6,
                'poster'           => 'posters/pegasus_3.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'The Curse',
                'description'      => 'Ancient spirits are unleashed upon archaeologists.',
                'genre'            => 'Horror',
                'duration'         => 105,
                'release_date'     => '2026-04-12',
                'rating'           => 6.1,
                'poster'           => 'posters/the_curse.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Kong Tao',
                'description'      => 'A dark exploration of traditional sorcery practices.',
                'genre'            => 'Horror',
                'duration'         => 108,
                'release_date'     => '2026-04-09',
                'rating'           => 6.7,
                'poster'           => 'posters/kong_tao.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Goat',
                'description'      => 'A small goat with big dreams joins a full-contact sport.',
                'genre'            => 'Animation',
                'duration'         => 100,
                'release_date'     => '2026-03-19',
                'rating'           => 7.3,
                'poster'           => 'posters/goat.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'Toy Story 5',
                'description'      => 'Woody and Buzz face a new threat: electronics.',
                'genre'            => 'Animation',
                'duration'         => 145,
                'release_date'     => '2026-06-18',
                'rating'           => 8.2,
                'poster'           => 'posters/toy_story.webp',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'title'            => 'The Mummy',
                'description'      => 'An ancient princess awakens bringing modern terrors.',
                'genre'            => 'Horror',
                'duration'         => 112,
                'release_date'     => '2026-04-16',
                'rating'           => 7.0,
                'poster'           => 'posters/the_mummy.jpg',
                'status'           => 'now_showing',
                'expected_release' => null,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
        ]);
    }
}